### ISSUE TITLE
dict: remove "idiomatic" for @subtype on cit[@type="translation"]

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/shawi-data#77]
We assume that translations which are not marked with a subtype are "idiomatic", so this is the implicit default. 

Should be removed both as value in `<valList>` and [schematron rule](https://github.com/acdh-oeaw/generic-dict-schema/blame/main/schema/acdh-ch-dicts.odd#L485)

**Comment by rausch-supola** [comment]
done https://github.com/acdh-oeaw/generic-dict-schema/commit/149b67f3efbb79774c4cfeb39eadd4c79cda7d55

I assume that the link to the schematron was in the wrong line (subtype proverb). The line concerning literal/idiomatic has already been fixed with another commit (https://github.com/acdh-oeaw/generic-dict-schema/commit/5bbc5a2faa93a824e0b50f5ab859f574da6411b6)
